version: '3'

#镜像说明:
#单机版：noearorg/luffy-jtl ，使用h2嵌入式数据库（不需初始化环境）
#集群版：noearorg/luffy-jtc ，使用mysql8数据库

services:
  navx:
    image: noearorg/luffy-jtl:1.4.2
    container_name: navx
    environment:
      - luffy.add=navx.noear     #添加luffy插件，多个以,隔开
      - luffy.home=/
      - luffy.init=/navx/__init  #启动后的初始化脚本
      - TZ=Asia/Shanghai          #设置时区
    ports:
      - "18080:8080"
    volumes:
      - "./luffy_ext:/luffy_ext"


